import type { Metadata } from 'next'
import LegalPage from '@/components/legal/LegalPage'

export const metadata: Metadata = { title: 'Terms of Service — CareerMind' }

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="October 2026"
      sections={[
        {
          title: 'Acceptance of terms',
          content:
            'CareerMind is operated by Suftnet Ltd, registered in England and Wales. By creating an account or ' +
            'using CareerMind you agree to these terms. If you do not agree, please do not use the service.',
        },
        {
          title: 'The service',
          content:
            'CareerMind provides AI-powered interview practice: generated interview questions, voice interviews ' +
            'with an AI interviewer, feedback, quizzes and flashcards. It is a practice tool only. Feedback and ' +
            'scores are generated by AI and may be inaccurate, and using CareerMind does not guarantee an ' +
            'interview, a job offer or any other outcome.',
        },
        {
          title: 'Accounts and the free interview',
          content:
            'You must give accurate details and keep your password secure. Each person may use one free ' +
            'interview, which requires a confirmed email address. Creating multiple accounts to obtain more ' +
            'free interviews is not allowed.',
        },
        {
          title: 'Payment terms',
          content:
            'Paid interviews are priced per session in pounds sterling and charged once, in advance, through ' +
            'Stripe. Because each interview is delivered as soon as it starts, payments are non-refundable once ' +
            'the interview has started. If a technical fault on our side prevents an interview from taking place, ' +
            'contact info@suftnet.com and we will refund or replace it. This does not affect your statutory rights.',
        },
        {
          title: 'Acceptable use',
          content:
            'You must not misuse CareerMind: no abusive, unlawful or harmful content; no attempts to disrupt, ' +
            'overload or reverse-engineer the service; no automated access; and no reselling or sharing of ' +
            'access. We may limit usage to keep the service fair and may suspend accounts that breach these terms.',
        },
        {
          title: 'Intellectual property',
          content:
            'CareerMind, its software, design and branding belong to Suftnet Ltd. You keep ownership of the ' +
            'content you provide, such as your CV and answers, and give us permission to process it only to ' +
            'provide the service to you. You may use your own feedback and study materials for your personal ' +
            'preparation.',
        },
        {
          title: 'Limitation of liability',
          content:
            'CareerMind is provided as is. To the extent permitted by law, Suftnet Ltd is not liable for indirect ' +
            'or consequential loss, or for decisions made based on AI-generated feedback, and our total liability ' +
            'is limited to the amount you paid us in the 12 months before the claim. Nothing in these terms limits ' +
            'liability that cannot be limited by law.',
        },
        {
          title: 'Governing law',
          content:
            'These terms are governed by the law of England and Wales, and the courts of England and Wales have ' +
            'jurisdiction over any dispute.',
        },
        {
          title: 'Contact',
          content: 'For questions about these terms, email info@suftnet.com.',
        },
      ]}
    />
  )
}
